name: "Terraform"
on:
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  terraform-format-test:
    uses: ./.github/workflows/terraform_format.yml
  terraform-graph:
    uses: synapsestudios/.github/.github/workflows/tf-graph.yml@master
    with:
      terraform_version: "1.3.7"
  terraform-docs:
    needs: [terraform-format-test, terraform-graph]
    uses: ./.github/workflows/documentation.yml
